language: node_js
sudo: false
node_js: "7"
addons:
  chrome: stable
branches:
  only:
    - master
    - /^greenkeeper/.*$/
cache:
  yarn: true
  directories:
    - ./node_modules
install:
  - yarn install
script:
  - yarn test
